name: Andrei Herasimchuk
favicon: null
layout_spectrum: 0.35715754935517907
typography_spectrum: 0.4553337886463851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5587060945108533
  lightness: 0.49639511154964566
  saturation: 0.951218914007768
  rhythmicContrast: 0.5908134335186332
purpose: []
